---
new_page_extension: md
auto_deploy: true
admin_path: asdf
webhook_url: 
sections: 
upload_dir: hugo/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
version: 0.31.1
